// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqskydhsxoqcsxxwwfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcXNreWRoc3hvcWNzeHh3d2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODM3MjAsImV4cCI6MjA1OTg1OTcyMH0.mu0s8IFTr4YMiQjU5C6nG83bV4cVC_YXszT6RTmTKJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);